AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a Security Group for the RDAP Cache service allowing SSH (restricted), HTTP, and HTTPS.'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'ID of the VPC where the security group should be created.'

  GroupName:
    Type: String
    Description: 'Name for the security group.'
    Default: 'rdap-cache-sg'

  GroupDescription:
    Type: String
    Description: 'Description for the security group.'
    Default: 'Security group for RDAP Cache service instance'

  SshCidrIp:
    Type: String
    Description: 'MANDATORY: CIDR block for allowed SSH access (e.g., Your.IP.Address/32). Do not use 0.0.0.0/0!'

Resources:
  RdapCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref GroupName
      GroupDescription: !Ref GroupDescription
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshCidrIp

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: !Ref GroupName

Outputs:
  SecurityGroupId:
    Description: 'The ID of the created Security Group'
    Value: !GetAtt RdapCacheSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  SecurityGroupName:
    Description: 'The Name of the created Security Group'
    Value: !Ref RdapCacheSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupName'
