AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a Security Group for the RDAP Cache service allowing SSH (restricted), HTTP, and HTTPS.'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'ID of the VPC where the security group should be created.'

  GroupName:
    Type: String
    Description: 'Name for the security group.'
    Default: 'rdap-cache-sg'

  GroupDescription:
    Type: String
    Description: 'Description for the security group.'
    Default: 'Security group for RDAP Cache service instance'

  SshCidrIp:
    Type: String
    Description: 'MANDATORY: CIDR block for allowed SSH access (e.g., Your.IP.Address/32). Do not use 0.0.0.0/0!'
    # No Default value - must be provided at deployment

Resources:
  RdapCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref GroupName
      GroupDescription: !Ref GroupDescription
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # --- SSH Access (Restricted by Parameter) ---
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshCidrIp # Uses the parameter value

        # --- HTTP Access (Public) ---
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allow HTTP from anywhere (for redirection)

        # --- HTTPS Access (Public) ---
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0 # Allow HTTPS from anywhere

      Tags:
        - Key: Name
          Value: !Ref GroupName

Outputs:
  SecurityGroupId:
    Description: 'The ID of the created Security Group'
    Value: !GetAtt RdapCacheSecurityGroup.GroupId # Export the actual Group ID
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId' # Make the export name unique

  SecurityGroupName:
    Description: 'The Name of the created Security Group'
    Value: !Ref RdapCacheSecurityGroup # Export the Name (Logical ID resolves to Name here)
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupName' # Make the export name unique
