#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e
# Treat unset variables as an error (optional but good practice)
# set -u
# Exit on error within pipes (optional but good practice)
# set -o pipefail

# --- Configuration Variables ---
# You can override these by setting environment variables before running the script
# Example: export PG_PASSWORD="your_secure_password" && sudo bash infra/install/1_postgres_setup.sh

DB_NAME="${PG_DB:-rdap_cache}"
DB_USER="${PG_USER:-rdap_user}"
# Generate a random password if PG_PASSWORD is not set
DB_PASSWORD="${PG_PASSWORD:-$(openssl rand -base64 16)}"

# --- Script Start ---
echo "-------------------------------------------"
echo "Starting PostgreSQL User/Database Setup..."
echo "Target Database: $DB_NAME"
echo "Target User:     $DB_USER"
# Only display password info if it was generated by the script
if [ -z "$PG_PASSWORD" ]; then
  echo "App User PW:   *** A random password will be generated ***"
else
  echo "App User PW:   *** Using provided \$PG_PASSWORD ***"
fi
echo "-------------------------------------------"
sleep 2 # Give user time to read

# --- Prerequisite Check ---
if ! command -v psql &> /dev/null
then
    echo "ERROR: 'psql' command not found. Please ensure PostgreSQL client is installed."
    echo "Hint: Run install_postgres.sh first."
    exit 1
fi

# --- 1. Set postgres superuser password ---
echo "Setting password for the 'postgres' superuser..."
read -s -p "Enter new password for the 'postgres' user (leave blank to skip): " POSTGRES_PASSWORD
echo # Add a newline after password input

if [ -z "$POSTGRES_PASSWORD" ]; then
  echo "No password entered. Skipping password change for 'postgres' user."
else
  # Use psql to execute the command as the 'postgres' user
  sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';" > /dev/null
  if [ $? -eq 0 ]; then
    echo "'postgres' user password successfully updated."
  else
    echo "ERROR: Failed to update 'postgres' user password."
    # Optionally exit here if this is critical
    # exit 1
  fi
fi
echo "-------------------------------------------"
sleep 1

# --- 2. Create Application User and Database ---
echo "Configuring application database '$DB_NAME' and user '$DB_USER'..."

# Use psql to execute SQL commands as the default 'postgres' superuser
# Use DO block to make user creation idempotent (doesn't fail if user exists)
sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$DB_USER') THEN CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD'; ELSE RAISE NOTICE 'User \"$DB_USER\" already exists, skipping creation.'; END IF; END \$\$;"

# Use DO block to make database creation idempotent
sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME') THEN CREATE DATABASE $DB_NAME; ELSE RAISE NOTICE 'Database \"$DB_NAME\" already exists, skipping creation.'; END IF; END \$\$;"

# --- 3. Grant Privileges ---
echo "Granting privileges to user '$DB_USER' on database '$DB_NAME'..."

# Grant connection privileges ON the database TO the user
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"

# Grant CREATEDB privilege TO the user (often needed for ORMs like Prisma for shadow databases)
sudo -u postgres psql -c "ALTER USER $DB_USER CREATEDB;"

# Grant USAGE and CREATE privileges ON the 'public' schema WITHIN the database
# Note: Must connect to the specific database (-d $DB_NAME) to grant schema permissions
sudo -u postgres psql -d $DB_NAME -c "GRANT USAGE, CREATE ON SCHEMA public TO $DB_USER;"

# --- 4. Output Summary ---
echo "-------------------------------------------"
echo "PostgreSQL User/Database setup completed!"
echo ""
echo "Database Name: $DB_NAME"
echo "Username:      $DB_USER"
# Display the password only if it was generated by this script run AND PG_PASSWORD was not set externally
if [ -z "$PG_PASSWORD" ]; then
    echo "Generated App User Password: $DB_PASSWORD"
    echo "*** Store this password securely! It won't be shown again. ***"
    echo "*** Use this in your .env file's DATABASE_URL. ***"
fi
echo ""
echo "Example DATABASE_URL for .env file:"
echo "DATABASE_URL=\"postgresql://$DB_USER:<PASSWORD>@localhost:5432/$DB_NAME\""
echo "(Replace <PASSWORD> with the actual password)"
echo "-------------------------------------------"

exit 0